# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: unit_tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
        pytorch-version: [ 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.10.0 ]

      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir numpy
        # Force the installation of a CPU-only PyTorch
        pip install torch==${{ matrix.pytorch-version }}+cpu -f https://download.pytorch.org/whl/torch_stable.html
        pip install --no-cache-dir '.[tests]'
    - name: Generate and upload the coverage report
      run: |
        # Imports work => compatible versions
        python -c "import torch; import torchaudio"
